### PR TITLE
EnderPearl fix

### PR DESCRIPTION
**Pull request by ElapsedDev**
Prevents players from teleporting to a one by one and glitching in!

### CODE REVIEW

**Comment by prosavage** [comment]
good job on figuring out how to do a PR. 
@RyderBelserion u get to review the code :)

**Comment by ElapsedDev** [comment]
Lol It was annoying on github setup is .... meanie

**Comment by prosavage** [comment]
Congrats!

**Comment by liz3** [comment]
xd

**Comment by ryderbelserion** [comment]
moist

**Pull request merged**
